In [1]:
#load need libraries
import pandas as pd
import numpy as np

In [4]:
A = [0, 1/3, 1/3, 1/3]
B = [1/2, 0, 0, 1/2]
C = [0, 0, 0, 1]
D = [0, 1/2, 1/2, 0]

In [5]:
m = np.array([A, B, C, D])
m = m.T
m

array([[ 0.        ,  0.5       ,  0.        ,  0.        ],
       [ 0.33333333,  0.        ,  0.        ,  0.5       ],
       [ 0.33333333,  0.        ,  0.        ,  0.5       ],
       [ 0.33333333,  0.5       ,  1.        ,  0.        ]])

In [56]:
l = len(m)
r = np.ones((l, 1)) * 1/l
d = .9

for i in range(40):
    r_init = r
    r = (1 - d)/l + d*(np.dot(m, r))
    ssd = np.square(r_init - r).sum()
    print(np.around(r, decimals=4).ravel())
    print(ssd)
    if ssd <= 1e-05:
        break

[ 0.1375  0.2125  0.2125  0.4375]
0.050625
[ 0.1206  0.2631  0.2631  0.3531]
0.0125296875
[ 0.1434  0.2201  0.2201  0.4164]
0.00822687890625
[ 0.124   0.2554  0.2554  0.3651]
0.00549605487305
[ 0.1399  0.2265  0.2265  0.407 ]
0.00367235332229
[ 0.1269  0.2501  0.2501  0.3728]
0.00245379709253
[ 0.1376  0.2308  0.2308  0.4008]
0.00163958087763
[ 0.1289  0.2466  0.2466  0.3779]
0.0010955369794
[ 0.136   0.2337  0.2337  0.3966]
0.000732017120721
[ 0.1302  0.2443  0.2443  0.3813]
0.000489120016124
[ 0.1349  0.2356  0.2356  0.3938]
0.000326820757878
[ 0.131   0.2427  0.2427  0.3836]
0.000218375458494
[ 0.1342  0.2369  0.2369  0.3919]
0.000145914357405
[ 0.1316  0.2416  0.2416  0.3851]
9.74972180658e-05
[ 0.1337  0.2378  0.2378  0.3907]
6.51457999035e-05
[ 0.132   0.2409  0.2409  0.3861]
4.35291932351e-05
[ 0.1334  0.2384  0.2384  0.3899]
2.90853848829e-05
[ 0.1323  0.2405  0.2405  0.3868]
1.94343049092e-05
[ 0.1332  0.2387  0.2387  0.3893]
1.29856355289e-05
[ 0.1324  0.2401  0.2401  0.3873]

1.0

In [16]:
l = len(m)
r = np.ones((l, 1)) * 1/l

#for i in range(20):
#    r = np.dot(m, r)
#    print(r.ravel())

r = np.dot(m, r)

print(r.ravel())
print(m)
r = np.dot(m, r)
print(r.ravel())

[ 0.125       0.20833333  0.20833333  0.45833333]
[[ 0.          0.5         0.          0.        ]
 [ 0.33333333  0.          0.          0.5       ]
 [ 0.33333333  0.          0.          0.5       ]
 [ 0.33333333  0.5         1.          0.        ]]
[ 0.10416667  0.27083333  0.27083333  0.35416667]


In [13]:
np.dot(m, r)

array([[ 0.13541667],
       [ 0.21180556],
       [ 0.21180556],
       [ 0.44097222]])

In [20]:
a = np.array([
 [1, 2]
 ])
a.shape == (1,2)
a = a.T
b = np.array([
 [3, 4],
 [5, 6]
 ])
b.shape == (2,2)

# Multiply
mm = np.dot(b,a)
#mm == [13, 16]
#mm.shape == (1,2)
mm

array([[11],
       [17]])